queerjs/website

- web/src/pages/_organizers.js
> Added Aveline to Organizers page

- web/src/helpers/useRainbow.js
Based on the Discord conversations... new flags 💓
> Add poly and philly stripes to useRainbow 

- web/src/helpers/useRainbow.js
Agender, aromantic, genderqueer and non binary... and I alphabetized the stripe names sorry 🔡 🎉 😬 (and yes after this I'm done adding flags)
> Add more flags to useRainbow

- web/src/pages/code-of-conduct.js
Fixes #19 😊 
Kind of a hacky solution, so let me know if there's a better way!
> Fix CoC email spacing

- data/london.yaml
Rachel can't speak anymore and Alex has stepped in to do a talk
> Remove Rachel, add Alex

- src/pages/index.js
> Count today's meetup as future, not past

- README.md
Add local development steps to README.
cc @SaraVieira
> docs: add local setup to README

- data/paris.yaml
Moving event to Dec, 3rd not to overlap with other Paris meetups linked to dotJS
> Move Paris event to Dec 3rd

- data/stockholm.yaml
Fixup my talk topic from QueerJS Stockholm.
cc @SaraVieira
> docs: add @codebytere's Stockholm talk title

- src/pages/_organizers.js
> add codebytere to organizers

- data/sf.yaml
Updated to reflect that @SaraVieira needs to protect her ears from planes for a bit.
cc @walaura @alxsavage
> fix: update MC/Speaker data for SF 11/2

- src/components/Thanks.js
- src/components/footer/elements.js
- src/components/footer/index.js
- src/components/header/elements.js
- src/components/layout/elements.js
- src/components/layout/index.js
- src/pages/_main.js
- src/pages/code-of-conduct.js
- src/pages/flags.js
- src/pages/report.js
Move the footer so that it's present on every page, and add a new page to allow for reporting of CoC violations a la https://wafflejs.com
> feat: add a CoC Reporting page

- data/paris.yaml
I forgot to update the Google calendar date :(
> Update queerjs paris google calendar

- README.md
@SaraVieira mentioned this in the Discord. Would be nice to have that info in the README rather than something ephemeral, for the next time someone else tries to update this :)
> Add note about .env.production file

- src/helpers/useRainbow.js
> The "poly" flag refers to polysexual, not polyamory

- data/berlin.yaml
> Add Berlin 2020!!!

- data/paris.yaml
> open CFP  for Paris NCrafts meetup

- data/paris.yaml
First 2 speakers recruited :tada:
> [data/paris]: add Guillaume and David to speakers

- src/pages/_organizers.js
Felt right 🤷‍♀ 
(but ofc @pducolin if you don't want to be listed here, also totally fine!)
> Move Paola to core team

- src/pages/_organizers.js
> Remove Carolyn

- data/online-2020-16.yaml
Updating date in website page url, hope this changes are enough
> online: move date in website url

- src/pages/code-of-conduct.js
Low priority.
I noticed a grammar issue and decided to tidy up some other words as well :)
> Tweak wording around Code of Conduct for grammar & simpler language

- data/online-2020-16.yaml
I've been coordinating captions!
> Adding myself as an organizer of the online meetup

- src/pages/_organizers.js
> Add Carolyn (again)

- data/online-2020-11-17.yaml
New online meetup! I used The internet as location vs Paris, let me know if you prefer it to be Paris only - personally would love to leave it open to at least EU speakers.
> Add Nov 17th online meetup

- data/online-2020-11-17.yaml
> add talks to online event 2020/11

- data/online-2020-11-17.yaml
Update Paul Louis talk title for next online event
> Update Paul Louis talk title

- data/online-2021-march.yaml
Add Datadog to sponsors for the 03/30 Online event
> Add Datadog to sponsors

- src/components/Info/Form.js
**Actual:**
When typing in plus one's name, spaces are being trimmed.
**Expected:**
When typing in plus one's name, spaces are allowed.
> Remove plus one's name trimming

- data/berlin-2023.yaml
Hello! Here's the barebones for Berlin July 2023, more info to be confirmed as I get a venue sorted!
> Berlin 2023

- src/pages/_organizers.js
> Updated my "stripes" in _organizers.js

- data/paris-2024.yaml
Add Flavio Gurgel to the speakers list and we are done with the CFP 🎉
> add flavio to Paris 2024 speakers list

- data/new-york-2024.yaml
> add speaker to new-york-2024

- data/paris-2024-october.yaml
> [paris] add Nicolò Ribaudo to the speakers list

- .github/workflows/build.yml
- .github/workflows/lint.yml
This PR changes Github workflow jobs to run on feature branches on `pull_request` events, and on `master` on `push` event
> [github] lint and build on PR once

- data/paris-2024-october.yaml
> [paris] add nicolo title

- data/paris-2024-october.yaml
https://github.com/queerjs/queerjs-talk-proposals/issues/69
> [paris] add Juliet Wang to speakers
